### ISSUE TITLE
Is this on cocoa pods?

### ISSUE THREAD

**Issue by wontruefree** [thoughtbot/courier-ios#16]
This is failing locally and I don't see it on the cocoa pods website `https://cocoapods.org/?q=courier-ios`

**Comment by alexshive** [comment]
Try this, worked for me:

`pod "Courier", :git => "https://github.com/thoughtbot/courier-ios.git"`

**Comment by alexshive** [comment]
It's also renamed to "courier-notifications"

**Comment by nickcharlton** [comment]
Hi @wontruefree & @alexshive! Did you get this working in the end? I'm going to go and fixup the README to make this clearer.

**Comment by wontruefree** [comment]
I did not the last time I used it. That was maybe a little over a week ago.

**Comment by nickcharlton** [comment]
I've opened a PR to fix up the wording and I'm going to do a release in the next few days (this will bring Swift 2.3/Xcode 8 support). For now, I'd recommend pulling from `master` directly.

I'm going to close this for now, but if you have a any other questions, please open an issue!
